# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
    - name: Update requirements.txt
      run: pipreqs --print . | sort > requirements.txt
    - name: git diff
      run: git diff
    - name: Check Git changes
      run: test "$(git diff --stat)" = ""

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.9
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: streamlit-webrtc-example
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
